import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import {
    Users,
    Crown,
    AlertTriangle,
    ShieldCheck,
    Search,
    TrendingUp,
    Clock,
    DollarSign,
    Award
} from "lucide-react";
import { ComprehensiveAnalytics, ClientAnalytics } from "../../lib/analyticsEngine";
import { formatMoney } from "../../lib/currencies";

interface ClientLtvDashboardProps {
    data: ComprehensiveAnalytics;
    currency: string;
}

export function ClientLtvDashboard({ data, currency }: ClientLtvDashboardProps) {
    const [searchQuery, setSearchQuery] = useState("");
    const [tierFilter, setTierFilter] = useState<string>("all");

    const filteredClients = useMemo(() => {
        return data.clientBreakdown.filter(c => {
            const matchesSearch = c.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                (c.company && c.company.toLowerCase().includes(searchQuery.toLowerCase()));
            const matchesTier = tierFilter === "all" || c.reliabilityTier.toLowerCase().includes(tierFilter.toLowerCase());
            return matchesSearch && matchesTier;
        });
    }, [data.clientBreakdown, searchQuery, tierFilter]);

    return (
        <div className="space-y-8">
            {/* Top 3 Strategic Metric Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {/* 1. Pareto 80/20 Concentration */}
                <div className="p-[1px] rounded-2xl bg-gradient-to-b from-blue-500/30 via-blue-500/10 to-transparent shadow-sm">
                    <div className="h-full p-5 rounded-[calc(1rem-1px)] bg-[#0C1322] daylight:bg-white border border-white/5 daylight:border-blue-200/60 flex flex-col justify-between">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-[11px] font-bold uppercase tracking-wider text-blue-400 daylight:text-blue-700 flex items-center gap-1.5">
                                <Award size={16} />
                                Pareto 80/20 Ratio
                            </span>
                        </div>
                        <div>
                            <div className="text-2xl sm:text-3xl font-black text-white daylight:text-[#090D16] font-mono">
                                {data.paretoTop20Share}%
                            </div>
                            <p className="text-xs text-slate-400 daylight:text-slate-600 font-medium mt-1">
                                Revenue generated by top 20% of clients
                            </p>
                        </div>
                    </div>
                </div>

                {/* 2. Customer Concentration Risk */}
                <div className={`p-[1px] rounded-2xl bg-gradient-to-b ${
                    data.isConcentrationRisk
                        ? "from-amber-500/30 via-amber-500/10"
                        : "from-emerald-500/30 via-emerald-500/10"
                } to-transparent shadow-sm`}>
                    <div className="h-full p-5 rounded-[calc(1rem-1px)] bg-[#0C1322] daylight:bg-white border border-white/5 daylight:border-slate-200 flex flex-col justify-between">
                        <div className="flex items-center justify-between mb-2">
                            <span className={`text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5 ${
                                data.isConcentrationRisk ? "text-amber-400 daylight:text-amber-800" : "text-emerald-400 daylight:text-emerald-700"
                            }`}>
                                {data.isConcentrationRisk ? <AlertTriangle size={16} /> : <ShieldCheck size={16} />}
                                Concentration Guardrail
                            </span>
                            <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-full ${
                                data.isConcentrationRisk
                                    ? "bg-amber-500/15 text-amber-400 daylight:bg-amber-50 daylight:text-amber-800"
                                    : "bg-emerald-500/15 text-emerald-400 daylight:bg-emerald-50 daylight:text-emerald-800"
                            }`}>
                                {data.isConcentrationRisk ? "HIGH RISK (>30%)" : "HEALTHY SPREAD"}
                            </span>
                        </div>
                        <div>
                            <div className="text-2xl sm:text-3xl font-black text-white daylight:text-[#090D16] font-mono">
                                {Math.round(data.topClientRevenueShare)}%
                            </div>
                            <p className="text-xs text-slate-400 daylight:text-slate-600 font-medium mt-1">
                                {data.isConcentrationRisk
                                    ? "Revenue is heavily dependent on #1 key account"
                                    : "Well-diversified portfolio distribution"}
                            </p>
                        </div>
                    </div>
                </div>

                {/* 3. Average Revenue Per Client (ARPC) */}
                <div className="p-[1px] rounded-2xl bg-gradient-to-b from-indigo-500/30 via-indigo-500/10 to-transparent shadow-sm">
                    <div className="h-full p-5 rounded-[calc(1rem-1px)] bg-[#0C1322] daylight:bg-white border border-white/5 daylight:border-indigo-200/60 flex flex-col justify-between">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-400 daylight:text-indigo-700 flex items-center gap-1.5">
                                <DollarSign size={16} />
                                Average Revenue / Client
                            </span>
                        </div>
                        <div>
                            <div className="text-2xl sm:text-3xl font-black text-white daylight:text-[#090D16] font-mono">
                                {formatMoney(data.averageRevenuePerClient, currency, currency)}
                            </div>
                            <p className="text-xs text-slate-400 daylight:text-slate-600 font-medium mt-1">
                                Lifetime value across active partnerships
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Payer Reliability Leaderboard & Portfolio Distribution */}
            <div className="p-[1px] rounded-2xl bg-gradient-to-b from-white/[0.08] to-transparent">
                <div className="p-6 rounded-[calc(1rem-1px)] bg-[#0C1322] daylight:bg-white border border-white/5 daylight:border-slate-200">
                    {/* Header & Filter Controls */}
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                        <div>
                            <span className="text-xs font-bold uppercase tracking-wider text-slate-400 daylight:text-slate-600 block mb-1">
                                Payer Settlement Scoring & Lifetime Value
                            </span>
                            <h2 className="text-xl font-black text-white daylight:text-[#090D16]">
                                Client Portfolio Intelligence
                            </h2>
                        </div>

                        {/* Search & Tier Pills */}
                        <div className="flex flex-wrap items-center gap-3">
                            <div className="relative">
                                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                                <input
                                    type="text"
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    placeholder="Filter by name..."
                                    className="pl-8 pr-3 py-1.5 rounded-xl bg-black/20 daylight:bg-slate-50 border border-white/10 daylight:border-slate-200 text-xs text-white daylight:text-slate-900 outline-none w-44 focus:border-blue-500"
                                />
                            </div>

                            <div className="flex items-center gap-1 bg-black/20 daylight:bg-slate-100 p-1 rounded-xl border border-white/5 daylight:border-slate-200">
                                {["all", "tier a", "tier b", "tier c", "tier d"].map(t => (
                                    <button
                                        key={t}
                                        onClick={() => setTierFilter(t)}
                                        className={`px-2.5 py-1 rounded-lg text-[11px] font-bold uppercase transition-all ${
                                            tierFilter === t
                                                ? "bg-blue-600 text-white"
                                                : "text-slate-400 daylight:text-slate-600 hover:text-white"
                                        }`}
                                    >
                                        {t.replace("tier ", "T-")}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Table View */}
                    <div className="overflow-x-auto rounded-xl border border-white/10 daylight:border-slate-200">
                        <table className="w-full text-left text-xs border-collapse">
                            <thead>
                                <tr className="border-b border-white/10 daylight:border-slate-200 bg-[#080D1A] daylight:bg-slate-50 text-slate-400 daylight:text-slate-700 uppercase text-[10px] font-bold">
                                    <th className="py-3 px-4">Client / Account</th>
                                    <th className="py-3 px-4 text-center">Reliability Tier</th>
                                    <th className="py-3 px-4 text-right">Avg Settlement</th>
                                    <th className="py-3 px-4 text-right">Cash Realized</th>
                                    <th className="py-3 px-4 text-right">Outstanding</th>
                                    <th className="py-3 px-4 text-right">Lifetime Total (LTV)</th>
                                    <th className="py-3 px-4 text-right">Portfolio Share</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-white/5 daylight:divide-slate-200 text-slate-300 daylight:text-slate-800">
                                {filteredClients.length === 0 ? (
                                    <tr>
                                        <td colSpan={7} className="py-8 text-center text-slate-400 italic">
                                            No clients match the selected criteria.
                                        </td>
                                    </tr>
                                ) : (
                                    filteredClients.map((c, idx) => (
                                        <tr key={c.clientId} className="hover:bg-white/[0.02] daylight:hover:bg-slate-50/70 transition-colors">
                                            <td className="py-3 px-4">
                                                <div className="flex items-center gap-2.5">
                                                    <div className="w-7 h-7 rounded-lg bg-blue-600/20 text-blue-400 daylight:bg-blue-50 daylight:text-blue-700 flex items-center justify-center font-bold text-xs">
                                                        {idx + 1}
                                                    </div>
                                                    <div>
                                                        <div className="font-bold text-white daylight:text-slate-900">{c.name}</div>
                                                        {c.company && (
                                                            <div className="text-[11px] text-slate-400 daylight:text-slate-500">{c.company}</div>
                                                        )}
                                                    </div>
                                                </div>
                                            </td>
                                            <td className="py-3 px-4 text-center">
                                                <span
                                                    className="px-2 py-0.5 rounded-full text-[10px] font-bold border"
                                                    style={{
                                                        color: c.tierBadgeColor,
                                                        borderColor: `${c.tierBadgeColor}40`,
                                                        backgroundColor: `${c.tierBadgeColor}15`
                                                    }}
                                                >
                                                    {c.reliabilityTier}
                                                </span>
                                            </td>
                                            <td className="py-3 px-4 text-right font-mono text-slate-400 daylight:text-slate-600">
                                                {c.avgDaysToPay} days
                                            </td>
                                            <td className="py-3 px-4 text-right font-mono text-emerald-400 daylight:text-emerald-700 font-semibold">
                                                {formatMoney(c.cashCollected, currency, currency)}
                                            </td>
                                            <td className="py-3 px-4 text-right font-mono text-amber-400 daylight:text-amber-800">
                                                {formatMoney(c.outstandingDue, currency, currency)}
                                            </td>
                                            <td className="py-3 px-4 text-right font-mono font-bold text-white daylight:text-[#090D16]">
                                                {formatMoney(c.totalRevenue, currency, currency)}
                                            </td>
                                            <td className="py-3 px-4 text-right font-mono">
                                                <div className="flex items-center justify-end gap-2">
                                                    <span className="font-bold text-blue-400 daylight:text-blue-700">{Math.round(c.revenueShare)}%</span>
                                                    <div className="w-12 h-1.5 rounded-full bg-white/10 daylight:bg-slate-200 overflow-hidden">
                                                        <div
                                                            className="h-full bg-blue-500 rounded-full"
                                                            style={{ width: `${Math.min(100, c.revenueShare)}%` }}
                                                        />
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
}
