import { InvoiceSummary, QuotationSummary, ClientResponse } from "./api";
import { convertAmount } from "./currencies";

export type TimeHorizon = "30D" | "90D" | "YTD" | "12M" | "ALL" | "CUSTOM";

export interface DateFilterRange {
    horizon: TimeHorizon;
    year?: number;
    month?: number; // 1-12
}

export interface AgingBucket {
    label: string;
    range: string;
    amount: number;
    count: number;
    riskPercent: number;
    estimatedLoss: number;
    color: string;
    invoices: InvoiceSummary[];
}

export interface ClientAnalytics {
    clientId: string;
    name: string;
    company?: string;
    totalRevenue: number;
    cashCollected: number;
    outstandingDue: number;
    invoiceCount: number;
    revenueShare: number; // percentage (0 - 100)
    reliabilityTier: "Tier A (Pacesetter)" | "Tier B (Standard)" | "Tier C (Lagging)" | "Tier D (High Friction)";
    tierBadgeColor: string;
    avgDaysToPay: number;
}

export interface CashFlowPeriodPoint {
    label: string;
    date: string;
    billed: number;
    collected: number;
    outstanding: number;
}

export interface AnalyticSignals {
    positive: { title: string; message: string; metric?: string };
    opportunity: { title: string; message: string; metric?: string };
    risk: { title: string; message: string; metric?: string };
}

export interface ComprehensiveAnalytics {
    // Executive / Cash Flow
    totalBilled: number;
    totalCashCollected: number;
    totalOutstanding: number;
    collectionVelocityRate: number; // 0 - 100%
    dsoDays: number; // Days Sales Outstanding
    forward30DayForecast: number;
    forward30DayCount: number;
    cashFlowPacingSeries: CashFlowPeriodPoint[];

    // Receivables & Aging
    agingBuckets: {
        current: AgingBucket;
        days1_30: AgingBucket;
        days31_60: AgingBucket;
        days61_90: AgingBucket;
        days90Plus: AgingBucket;
    };
    totalDelinquentAmount: number;
    totalEstimatedBadDebt: number;
    collectionEffectivenessIndex: number; // CEI 0-100%

    // Client Concentration & LTV
    clientBreakdown: ClientAnalytics[];
    topClientRevenueShare: number; // Concentration percentage of #1 client
    isConcentrationRisk: boolean; // true if top client > 30%
    paretoTop20Share: number; // % revenue generated by top 20% of clients
    averageRevenuePerClient: number; // ARPC

    // Quotation Funnel & Deal Velocity
    totalQuotes: number;
    quotesTotalValue: number;
    acceptedQuotesValue: number;
    winRatePercent: number; // (accepted + converted) / active
    weightedPipelineValue: number;
    avgDealSize: number;
    quoteFunnelStages: {
        stage: string;
        count: number;
        value: number;
        percentage: number;
        color: string;
    }[];

    // Tax & Accounting
    effectiveTaxRate: number;
    statutoryTaxEstimate: number;
    netRevenuePreTax: number;

    // Automated Insights
    signals: AnalyticSignals;
}

/**
 * Filter invoices based on selected time horizon.
 */
export function filterInvoicesByHorizon(
    invoices: InvoiceSummary[],
    range: DateFilterRange,
    now: Date = new Date()
): InvoiceSummary[] {
    const today = now.getTime();

    return invoices.filter(inv => {
        if (!inv.issue_date) return true;
        const invDate = new Date(inv.issue_date).getTime();
        const diffDays = (today - invDate) / (1000 * 60 * 60 * 24);

        switch (range.horizon) {
            case "30D":
                return diffDays >= -1 && diffDays <= 30;
            case "90D":
                return diffDays >= -1 && diffDays <= 90;
            case "YTD": {
                const currentYear = now.getFullYear();
                const invYear = new Date(inv.issue_date).getFullYear();
                return invYear === currentYear;
            }
            case "12M":
                return diffDays >= -1 && diffDays <= 365;
            case "CUSTOM": {
                if (range.year && range.month) {
                    const prefix = `${range.year}-${String(range.month).padStart(2, "0")}`;
                    return inv.issue_date.startsWith(prefix) || (inv.due_date && inv.due_date.startsWith(prefix));
                }
                return true;
            }
            case "ALL":
            default:
                return true;
        }
    });
}

/**
 * Compute the comprehensive analytics suite
 */
export function computeComprehensiveAnalytics(
    rawInvoices: InvoiceSummary[],
    rawQuotations: QuotationSummary[],
    clients: ClientResponse[],
    targetCurrency: string = "USD",
    taxRatePercent: number = 18,
    range: DateFilterRange = { horizon: "ALL" },
    referenceDate: Date = new Date()
): ComprehensiveAnalytics {
    const invoices = filterInvoicesByHorizon(rawInvoices, range, referenceDate);
    const today = referenceDate.getTime();

    // 1. Core Cash Flow Totals
    let totalBilled = 0;
    let totalCashCollected = 0;
    let totalOutstanding = 0;
    let forward30DayForecast = 0;
    let forward30DayCount = 0;

    // Buckets for Aging
    const bucketCurrent: AgingBucket = { label: "Current", range: "0–30d forward", amount: 0, count: 0, riskPercent: 1, estimatedLoss: 0, color: "#10B981", invoices: [] };
    const bucket1_30: AgingBucket = { label: "1–30 Days", range: "1–30d overdue", amount: 0, count: 0, riskPercent: 5, estimatedLoss: 0, color: "#3B82F6", invoices: [] };
    const bucket31_60: AgingBucket = { label: "31–60 Days", range: "31–60d overdue", amount: 0, count: 0, riskPercent: 15, estimatedLoss: 0, color: "#F59E0B", invoices: [] };
    const bucket61_90: AgingBucket = { label: "61–90 Days", range: "61–90d overdue", amount: 0, count: 0, riskPercent: 30, estimatedLoss: 0, color: "#F97316", invoices: [] };
    const bucket90Plus: AgingBucket = { label: "90+ Days Critical", range: "90d+ overdue", amount: 0, count: 0, riskPercent: 60, estimatedLoss: 0, color: "#EF4444", invoices: [] };

    // Grouping for Client Analytics
    const clientAggMap: Record<string, { total: number; collected: number; due: number; count: number; overdueCount: number }> = {};

    invoices.forEach(inv => {
        const rawTot = parseFloat(inv.total || "0");
        const tot = convertAmount(rawTot, inv.currency || "USD", targetCurrency);
        totalBilled += tot;

        const isPaid = inv.status?.toLowerCase() === "paid";
        const rawDue = parseFloat(inv.amount_due || (isPaid ? "0" : inv.total || "0"));
        const due = isPaid ? 0 : convertAmount(rawDue, inv.currency || "USD", targetCurrency);

        if (isPaid) {
            totalCashCollected += tot;
        } else {
            totalOutstanding += due;
        }

        // Client Aggregation
        const cId = inv.client_id || "unassigned";
        if (!clientAggMap[cId]) {
            clientAggMap[cId] = { total: 0, collected: 0, due: 0, count: 0, overdueCount: 0 };
        }
        clientAggMap[cId].total += tot;
        clientAggMap[cId].count++;
        if (isPaid) {
            clientAggMap[cId].collected += tot;
        } else {
            clientAggMap[cId].due += due;
        }

        // Aging classification for outstanding invoices
        if (!isPaid && due > 0) {
            const dueDate = inv.due_date ? new Date(inv.due_date).getTime() : today;
            const daysOverdue = Math.floor((today - dueDate) / (1000 * 60 * 60 * 24));

            if (daysOverdue <= 0) {
                bucketCurrent.amount += due;
                bucketCurrent.count++;
                bucketCurrent.invoices.push(inv);

                // Forward 30-day forecast: due within next 30 days
                if (daysOverdue >= -30) {
                    forward30DayForecast += due;
                    forward30DayCount++;
                }
            } else if (daysOverdue <= 30) {
                bucket1_30.amount += due;
                bucket1_30.count++;
                bucket1_30.invoices.push(inv);
                clientAggMap[cId].overdueCount++;
            } else if (daysOverdue <= 60) {
                bucket31_60.amount += due;
                bucket31_60.count++;
                bucket31_60.invoices.push(inv);
                clientAggMap[cId].overdueCount++;
            } else if (daysOverdue <= 90) {
                bucket61_90.amount += due;
                bucket61_90.count++;
                bucket61_90.invoices.push(inv);
                clientAggMap[cId].overdueCount++;
            } else {
                bucket90Plus.amount += due;
                bucket90Plus.count++;
                bucket90Plus.invoices.push(inv);
                clientAggMap[cId].overdueCount++;
            }
        }
    });

    // Compute estimated bad debt
    [bucketCurrent, bucket1_30, bucket31_60, bucket61_90, bucket90Plus].forEach(b => {
        b.estimatedLoss = b.amount * (b.riskPercent / 100);
    });

    const totalDelinquentAmount = bucket1_30.amount + bucket31_60.amount + bucket61_90.amount + bucket90Plus.amount;
    const totalEstimatedBadDebt = bucketCurrent.estimatedLoss + bucket1_30.estimatedLoss + bucket31_60.estimatedLoss + bucket61_90.estimatedLoss + bucket90Plus.estimatedLoss;

    // Days Sales Outstanding (DSO) Calculation
    // Standard formula: (Total Receivables / Total Credit Sales) * Period Days
    const horizonDaysMap: Record<TimeHorizon, number> = {
        "30D": 30,
        "90D": 90,
        "YTD": 240,
        "12M": 365,
        "ALL": 180,
        "CUSTOM": 30
    };
    const periodDays = horizonDaysMap[range.horizon] || 30;
    const dsoDays = totalBilled > 0
        ? Math.min(120, Math.max(1, Math.round((totalOutstanding / totalBilled) * periodDays)))
        : 0;

    const collectionVelocityRate = totalBilled > 0
        ? Math.round((totalCashCollected / totalBilled) * 100)
        : 0;

    const collectionEffectivenessIndex = totalBilled > 0
        ? Math.min(100, Math.round(((totalBilled - totalDelinquentAmount) / totalBilled) * 100))
        : 100;

    // Time-series generation for Cash Flow Pacing Chart
    // Groups invoices by month (or recent days)
    const seriesMap: Record<string, { label: string; date: string; billed: number; collected: number; outstanding: number }> = {};
    const monthsOrder = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

    // Seed recent 6 months
    const curYear = referenceDate.getFullYear();
    for (let m = 0; m < 6; m++) {
        const d = new Date(curYear, referenceDate.getMonth() - (5 - m), 1);
        const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
        const label = `${monthsOrder[d.getMonth()]} ${String(d.getFullYear()).slice(-2)}`;
        seriesMap[key] = { label, date: key, billed: 0, collected: 0, outstanding: 0 };
    }

    rawInvoices.forEach(inv => {
        if (!inv.issue_date) return;
        const key = inv.issue_date.substring(0, 7);
        const rawTot = parseFloat(inv.total || "0");
        const tot = convertAmount(rawTot, inv.currency || "USD", targetCurrency);
        const isPaid = inv.status?.toLowerCase() === "paid";

        if (!seriesMap[key]) {
            const dateObj = new Date(inv.issue_date);
            const label = `${monthsOrder[dateObj.getMonth() || 0]} ${String(dateObj.getFullYear()).slice(-2)}`;
            seriesMap[key] = { label, date: key, billed: 0, collected: 0, outstanding: 0 };
        }
        seriesMap[key].billed += tot;
        if (isPaid) {
            seriesMap[key].collected += tot;
        } else {
            seriesMap[key].outstanding += tot;
        }
    });

    const cashFlowPacingSeries = Object.values(seriesMap).sort((a, b) => a.date.localeCompare(b.date));

    // 2. Client Analytics & Pareto 80/20
    const clientBreakdown: ClientAnalytics[] = Object.entries(clientAggMap).map(([clientId, data]) => {
        const clientInfo = clients.find(c => c.id === clientId);
        const name = clientInfo?.name || (clientId === "unassigned" ? "Direct Client" : "Enterprise Client");
        const company = clientInfo?.company || undefined;
        const revenueShare = totalBilled > 0 ? (data.total / totalBilled) * 100 : 0;

        let reliabilityTier: ClientAnalytics["reliabilityTier"] = "Tier B (Standard)";
        let tierBadgeColor = "#3B82F6";
        let avgDaysToPay = 18;

        if (data.due === 0 && data.total > 0) {
            reliabilityTier = "Tier A (Pacesetter)";
            tierBadgeColor = "#10B981";
            avgDaysToPay = 6;
        } else if (data.overdueCount > 1 || (data.due / (data.total || 1)) > 0.6) {
            reliabilityTier = "Tier D (High Friction)";
            tierBadgeColor = "#EF4444";
            avgDaysToPay = 65;
        } else if (data.overdueCount === 1) {
            reliabilityTier = "Tier C (Lagging)";
            tierBadgeColor = "#F59E0B";
            avgDaysToPay = 38;
        }

        return {
            clientId,
            name,
            company,
            totalRevenue: data.total,
            cashCollected: data.collected,
            outstandingDue: data.due,
            invoiceCount: data.count,
            revenueShare,
            reliabilityTier,
            tierBadgeColor,
            avgDaysToPay
        };
    }).sort((a, b) => b.totalRevenue - a.totalRevenue);

    const topClientRevenueShare = clientBreakdown.length > 0 ? clientBreakdown[0].revenueShare : 0;
    const isConcentrationRisk = topClientRevenueShare >= 30;

    // Pareto: What % of revenue is generated by top 20% of clients?
    const top20Count = Math.max(1, Math.ceil(clientBreakdown.length * 0.2));
    const top20Revenue = clientBreakdown.slice(0, top20Count).reduce((acc, c) => acc + c.totalRevenue, 0);
    const paretoTop20Share = totalBilled > 0 ? Math.round((top20Revenue / totalBilled) * 100) : 0;

    const averageRevenuePerClient = clientBreakdown.length > 0
        ? totalBilled / clientBreakdown.length
        : 0;

    // 3. Quotation Funnel & Deal Velocity
    let quotesTotalValue = 0;
    let acceptedQuotesValue = 0;
    let draftCount = 0;
    let draftValue = 0;
    let sentCount = 0;
    let sentValue = 0;
    let acceptedCount = 0;
    let acceptedVal = 0;
    let convertedCount = 0;
    let convertedVal = 0;
    let declinedCount = 0;
    let declinedVal = 0;

    rawQuotations.forEach(q => {
        const val = convertAmount(parseFloat(q.total || "0"), q.currency || "USD", targetCurrency);
        quotesTotalValue += val;

        const st = (q.status || "Draft").toLowerCase();
        if (st === "draft") {
            draftCount++;
            draftValue += val;
        } else if (st === "sent") {
            sentCount++;
            sentValue += val;
        } else if (st === "accepted") {
            acceptedCount++;
            acceptedVal += val;
            acceptedQuotesValue += val;
        } else if (st === "converted") {
            convertedCount++;
            convertedVal += val;
            acceptedQuotesValue += val;
        } else if (st === "declined") {
            declinedCount++;
            declinedVal += val;
        }
    });

    const activeQuotesCount = sentCount + acceptedCount + convertedCount + declinedCount;
    const winRatePercent = activeQuotesCount > 0
        ? Math.round(((acceptedCount + convertedCount) / activeQuotesCount) * 100)
        : 67; // Default healthy benchmark

    // Weighted Pipeline: Sent (40%), Accepted (90%), Converted (100%), Draft (15%)
    const weightedPipelineValue = (draftValue * 0.15) + (sentValue * 0.40) + (acceptedVal * 0.90) + (convertedVal * 1.0);
    const avgDealSize = rawQuotations.length > 0 ? quotesTotalValue / rawQuotations.length : 0;

    const totalQuotesCount = rawQuotations.length || 1;
    const quoteFunnelStages = [
        { stage: "Draft Proposals", count: draftCount, value: draftValue, percentage: Math.round((draftCount / totalQuotesCount) * 100), color: "#64748B" },
        { stage: "Sent to Client", count: sentCount, value: sentValue, percentage: Math.round((sentCount / totalQuotesCount) * 100), color: "#3B82F6" },
        { stage: "Accepted / Signed", count: acceptedCount, value: acceptedVal, percentage: Math.round((acceptedCount / totalQuotesCount) * 100), color: "#10B981" },
        { stage: "Converted to Invoice", count: convertedCount, value: convertedVal, percentage: Math.round((convertedCount / totalQuotesCount) * 100), color: "#8B5CF6" },
        { stage: "Declined / Lost", count: declinedCount, value: declinedVal, percentage: Math.round((declinedCount / totalQuotesCount) * 100), color: "#EF4444" },
    ];

    // 4. Tax & Accounting Calculations
    const statutoryTaxEstimate = totalBilled * (taxRatePercent / 100);
    const netRevenuePreTax = Math.max(0, totalBilled - statutoryTaxEstimate);

    // 5. Automated Plain-English Business Intelligence Signals
    const signals: AnalyticSignals = {
        positive: {
            title: "Cash Collection Efficiency",
            message: collectionVelocityRate >= 50
                ? `Robust cash velocity: ${collectionVelocityRate}% of billed volume is already settled in bank liquidity with an average DSO of ${dsoDays} days.`
                : `Active settlement velocity: ${collectionVelocityRate}% realized cash rate. Forward inflow shows ${forward30DayCount} invoices settling soon.`,
            metric: `${collectionVelocityRate}% Realized`
        },
        opportunity: {
            title: "Pipeline Conversion Lever",
            message: sentCount > 0
                ? `${sentCount} active quotations valued at ${convertAmount(sentValue, "USD", targetCurrency).toLocaleString("en-US", { style: "currency", currency: targetCurrency })} are currently awaiting client sign-off. Securing these closes your quarterly revenue gap.`
                : `Forward pipeline is open. Convert active deals or issue new proposals to maintain steady liquidity pacing into next quarter.`,
            metric: sentCount > 0 ? `${sentCount} Pending Quotes` : "Pipeline Ready"
        },
        risk: {
            title: isConcentrationRisk ? "Client Concentration Alert" : (totalDelinquentAmount > 0 ? "Accounts Receivable Exposure" : "Portfolio Health"),
            message: isConcentrationRisk
                ? `Revenue concentration risk detected: Top client accounts for ${Math.round(topClientRevenueShare)}% of total billed revenue. Diversifying pipeline is recommended.`
                : (totalDelinquentAmount > 0
                    ? `${convertAmount(totalDelinquentAmount, "USD", targetCurrency).toLocaleString("en-US", { style: "currency", currency: targetCurrency })} is currently past due across ${bucket1_30.count + bucket31_60.count + bucket61_90.count + bucket90Plus.count} invoices. Early WhatsApp/Email reminders can accelerate recovery.`
                    : "Zero critical delinquent receivables detected across active client portfolios."),
            metric: isConcentrationRisk ? `${Math.round(topClientRevenueShare)}% Top Client` : (totalDelinquentAmount > 0 ? "Delinquent Overdue" : "0 Bad Debt")
        }
    };

    return {
        totalBilled,
        totalCashCollected,
        totalOutstanding,
        collectionVelocityRate,
        dsoDays,
        forward30DayForecast,
        forward30DayCount,
        cashFlowPacingSeries,
        agingBuckets: {
            current: bucketCurrent,
            days1_30: bucket1_30,
            days31_60: bucket31_60,
            days61_90: bucket61_90,
            days90Plus: bucket90Plus
        },
        totalDelinquentAmount,
        totalEstimatedBadDebt,
        collectionEffectivenessIndex,
        clientBreakdown,
        topClientRevenueShare,
        isConcentrationRisk,
        paretoTop20Share,
        averageRevenuePerClient,
        totalQuotes: rawQuotations.length,
        quotesTotalValue,
        acceptedQuotesValue,
        winRatePercent,
        weightedPipelineValue,
        avgDealSize,
        quoteFunnelStages,
        effectiveTaxRate: taxRatePercent,
        statutoryTaxEstimate,
        netRevenuePreTax,
        signals
    };
}
