/// PDF generation module — uses headless Chrome via the `headless_chrome` crate.
/// Captures vector-perfect PDFs from HTML/URL.

use anyhow::Result;
use headless_chrome::{Browser, LaunchOptions};
use std::path::PathBuf;
use std::fs;

pub struct PdfGenerator {
    output_dir: PathBuf,
}

impl PdfGenerator {
    pub fn new(output_dir: PathBuf) -> Self {
        fs::create_dir_all(&output_dir).ok();
        Self { output_dir }
    }

    /// Generates a PDF from a given URL or local file path.
    /// Returns the path to the generated PDF.
    pub fn generate_from_url(&self, url: &str, output_filename: &str) -> Result<PathBuf> {
        let browser = Browser::new(LaunchOptions {
            headless: true,
            ..Default::default()
        })?;

        let tab = browser.new_tab()?;
        tab.navigate_to(url)?;
        
        // Wait for network idle or specific selector if needed
        tab.wait_until_navigated()?;

        let pdf_data = tab.print_to_pdf(None)?;
        
        let output_path = self.output_dir.join(output_filename);
        fs::write(&output_path, pdf_data)?;

        Ok(output_path)
    }

    /// Helper to generate PDF for a specific invoice ID by rendering a local template or app route.
    /// In a real app, this would point to a specific invoice view URL served by the app.
    pub fn generate_invoice_pdf(&self, invoice_id: &str) -> Result<PathBuf> {
        // For now, we point to a placeholder URL. In production, this would be localhost:<port>/invoice/<id>/print
        let url = format!("data:text/html,<h1>Invoice {}</h1><p>Generated by InvoiceFlow</p>", invoice_id); 
        self.generate_from_url(&url, &format!("invoice-{}.pdf", invoice_id))
    }
}
